Updated README
SuperSecureHuman/anokha-2024 pull request #178
Opened 2024-10-16 04:02 UTC by Abhinav-ark

Adding Documentation to README (In Progress...)

Closes #177

2024-12-04 15:39 UTC, Thanus-Kumaar commented
Made the necessary changes to the readme.md, do check @Ashrockzzz2003 @Abhinav-ark

2024-12-04 15:50 UTC, Ashrockzzz2003 requested changes
Awesome work @Thanus-Kumaar 
Let's add links to other repos here. 

Backend, Mobile app, admin app, qr scan ... etc

2024-12-04 23:58 UTC, Abhinav-ark reviewed
@Thanus-Kumaar  `Profile Page` and `View Team Event Registation Details` Are Missing.

2024-12-04 23:58 UTC, Abhinav-ark commented on README.md
> +Manage and view your transactions effortlessly.
The Video is to `View Registration and Submit Feedback`. Transactions Will be In Profile Page.

2024-12-06 10:39 UTC, Ashrockzzz2003 approved these changes
LGTM

2024-12-06 10:39 UTC, merged

2024-12-06 15:17 UTC, Abhinav-ark reviewed
Look into following changes.

2024-12-06 15:17 UTC, Abhinav-ark commented on README.md
> +## 💳 View Transactions
This is not just transactions. Change Emoji also.

2024-12-06 15:17 UTC, Abhinav-ark commented on README.md
> +## Profile Page
Why does this h2 not have an emoji? Use 👤.

2024-12-06 15:17 UTC, Abhinav-ark commented on README.md
> +https://github.com/user-attachments/assets/ed589656-b210-4b45-a697-c43e7c216e2d
View Transactions functionality not showcased in profile page.